default:
  language_version:
    python: python3.13.1

repos:
  - repo: https://github.com/pycqa/isort
    rev: 6.0.0
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.2
    hooks:
      - id: flake8
        args: [--config, .flake8]
